# Generated by Django 4.1.6 on 2023-08-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatelineitem',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
        migrations.AddField(
            model_name='estimatelineitem',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor'),
        ),
        migrations.AddField(
            model_name='exhibitlineitem',
            name='exhibit_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.exhibit'),
            preserve_default=False,
        ),
    ]
