# Generated by Django 4.1.6 on 2023-08-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(verbose_name='Generated')),
                ('pdf', models.FileField(default=None, upload_to='projectmanagement/reports/')),
            ],
        ),
    ]
